name: Ejecutar Cuadernos Jupyter

on:
  push:
    branches:
      - main  # o el nombre de tu rama principal

jobs:
  ejecutar_cuadernos:
    runs-on: ubuntu-latest

    steps:
      - name: Configurar Git
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Checkout del Código
        uses: actions/checkout@v2

      - name: Instalar Dependencias
        run: |
          pip install -r requirements.txt
          pip install nbconvert
          pip install papermill

      - name: Ejecutar Cuaderno A
        run: papermill cuaderno_A.ipynb output_A.ipynb

      - name: Ejecutar Cuaderno B
        run: papermill cuaderno_B.ipynb output_B.ipynb

      - name: Commit y Push de Resultados
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add output_A.ipynb output_B.ipynb
          git commit -m "Actualizar resultados de los cuadernos"
          git push
